### PR TITLE
Jbaker/refactor focus tracking

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #92, #93

## Summary:

Refactor of how focus tracking is handled to auto-close the bib when moving focus away from the datepicker.

Improve validation workflow for adding/removing the `error` attribute before a value is set for the datepicker.

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by jordanjones243 — CHANGES_REQUESTED** [review]
When tabbing via keyboard through the api page to the first example, I was able to open to up the calendar, but when I continued tabbing through and reached the second example, but the calendar from the first example never closed.

The behavior expected is for bibs to close once focus is blurred from the datepicker element and it's contents.

**Review by jordanjones243 — CHANGES_REQUESTED** [review]
The "Basic" example on the API page seems to be getting an incorrect error state when the element gets focus, then blurred.

**Comment by jordanjones243** [comment]
After a datepicker is in an error state and then focus is given to it, the border-width seems to be too thin.

**Comment by jason-capsule42** [comment]
> After a datepicker is in an error state and then focus is given to it, the border-width seems to be too thin.

I noticed the same but this is coming from dropdown and needs to be looked at there.

**Review by jordanjones243 — APPROVED** [review]

**Pull request merged**
